package view;

import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 */
public class HomeView extends JFrame
{

    private final DefaultListModel model;

    public HomeView()
    {
        this.initComponents();
        this.model = new DefaultListModel();

        super.setVisible(true);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        GB = new ButtonGroup();
        jMenu2 = new JMenu();
        comboBox = new JComboBox();
        jScrollPane1 = new JScrollPane();
        numberList = new JList();
        buttonNewNumber = new JButton();
        radioMale = new JRadioButton();
        radioFemale = new JRadioButton();
        fieldDate = new JTextField();
        fieldNacionality = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenuItemNew = new JMenuItem();
        jMenuItemEdit = new JMenuItem();
        jMenuItemDel = new JMenuItem();
        jMenu3 = new JMenu();
        jMenuItemConfig = new JMenuItem();
        jMenuItemExit = new JMenuItem();

        GB.add(radioMale); GB.add(radioFemale);

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");

        jScrollPane1.setViewportView(numberList);

        buttonNewNumber.setText("Novo Número");

        radioMale.setText("Masculino");

        radioFemale.setText("Feminino");

        fieldDate.setEditable(false);

        fieldNacionality.setEditable(false);

        jLabel1.setText("Data de nascimento");

        jLabel2.setText("Nacionalidade");

        jLabel3.setText("Sexo");

        jMenu1.setMnemonic('c');
        jMenu1.setText("Contato");

        jMenuItemNew.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_I, InputEvent.CTRL_DOWN_MASK));
        jMenuItemNew.setMnemonic('i');
        jMenuItemNew.setText("Novo");
        jMenuItemNew.setToolTipText("");
        jMenu1.add(jMenuItemNew);

        jMenuItemEdit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, InputEvent.CTRL_DOWN_MASK));
        jMenuItemEdit.setMnemonic('a');
        jMenuItemEdit.setText("Editar");
        jMenu1.add(jMenuItemEdit);

        jMenuItemDel.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, InputEvent.CTRL_DOWN_MASK));
        jMenuItemDel.setMnemonic('e');
        jMenuItemDel.setText("Excluir");
        jMenu1.add(jMenuItemDel);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ferramentas");

        jMenuItemConfig.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_DOWN_MASK));
        jMenuItemConfig.setMnemonic('c');
        jMenuItemConfig.setText("Configurações");
        jMenu3.add(jMenuItemConfig);

        jMenuItemExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK));
        jMenuItemExit.setText("Sair");
        jMenu3.add(jMenuItemExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBox, 0, 322, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(radioMale)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(radioFemale)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldDate)
                                            .addComponent(fieldNacionality)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(buttonNewNumber)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNacionality, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFemale)
                    .addComponent(jLabel3))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMale)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewNumber)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultListModel getModel()
    {
        return this.model;
    }

    public JButton getButtonNewNumber()
    {
        return this.buttonNewNumber;
    }

    public JComboBox getComboBox()
    {
        return this.comboBox;
    }

    public JTextField getFieldDate()
    {
        return this.fieldDate;
    }

    public JTextField getFieldNacionality()
    {
        return this.fieldNacionality;
    }

    public JList getNumberList()
    {
        return this.numberList;
    }

    public JRadioButton getRadioFemale()
    {
        return this.radioFemale;
    }

    public JRadioButton getRadioMale()
    {
        return this.radioMale;
    }

    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    private void foo()
    {
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals(info.getName()) )
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup GB;
    private JButton buttonNewNumber;
    private JComboBox comboBox;
    private JTextField fieldDate;
    private JTextField fieldNacionality;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenu jMenu3;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItemConfig;
    private JMenuItem jMenuItemDel;
    private JMenuItem jMenuItemEdit;
    private JMenuItem jMenuItemExit;
    private JMenuItem jMenuItemNew;
    private JScrollPane jScrollPane1;
    private JList numberList;
    private JRadioButton radioFemale;
    private JRadioButton radioMale;
    // End of variables declaration//GEN-END:variables
}